/**
 * Historical recovery (remedial class) sessions conducted before this system
 * tracked them, hand-transcribed from an operations spreadsheet covering
 * MRV, NRI and CDU (2026-07-04 through 2026-08-11).
 *
 * `sheetSubject` is the short subject code as written in the spreadsheet --
 * it is NOT necessarily the exact value stored in recovery_topics.subject for
 * that campus (MRV and NRI don't use CDU's short-code convention), so the
 * import script resolves each topic by TITLE across every subject for the
 * campus and trusts whichever subject the matched topic actually belongs to.
 * `sheetSubject` is kept only for cross-checking / logging.
 *
 * `skip: true` rows are sessions that did not actually happen (cancelled, no
 * students joined, 0 joinees) -- per instruction, these are NOT written as
 * "cancelled" session records; they are simply left out entirely so the
 * corresponding topics stay in their default "needs recovery" state.
 */

export const MRV_CAMPUS = "Malla Reddy Vishwavidyapeeth";
export const NRI_CAMPUS = "NRI";
export const CDU_CAMPUS_NAME = "Chaitanya Deemed-to-be University";

export interface HistoricalRecoverySessionRow {
  /** Canonical campus name as stored in recovery_topics/recovery_sessions. */
  campus: string;
  instructorName: string;
  employeeId: string | null;
  /** Short subject code from the spreadsheet -- reference only, see file doc. */
  sheetSubject: string;
  /** ISO yyyy-mm-dd */
  scheduledDate: string;
  startTime: string;
  endTime: string;
  remarks: string;
  qaReportUrls: string[];
  /** Topic titles as written in the spreadsheet, one per delivered topic. */
  topics: string[];
  /** True = session did not happen; do not create any record for this row. */
  skip: boolean;
  skipReason?: string;
  /** True = instructor's own remark flags something worth a human look. */
  flagForReview?: boolean;
  flagReason?: string;
}

export const HISTORICAL_RECOVERY_SESSIONS: HistoricalRecoverySessionRow[] = [
  {
    campus: MRV_CAMPUS,
    instructorName: "Ayush Kundal",
    employeeId: null,
    sheetSubject: "DSA",
    scheduledDate: "2026-07-04",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Not informed in the initial days so no qa report generated",
    qaReportUrls: [],
    topics: ["Hashing", "Prefix sum K"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Tharuni",
    employeeId: null,
    sheetSubject: "GenAi",
    scheduledDate: "2026-07-06",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/fe07e855-34b3-42bd-8630-718687146394",
    ],
    // Sheet listed this as one combined entry ("part 1,2"); the dry run's
    // closest-match suggestions confirmed these are two separate recovery_topics
    // rows ("... | Part 1" and "... | Part 2"), so split them here.
    topics: [
      "Build Your Own AI News Summarizer | Part 1",
      "Build Your Own AI News Summarizer | Part 2",
    ],
    skip: false,
  },
  {
    campus: NRI_CAMPUS,
    instructorName: "Praveen",
    employeeId: null,
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-06",
    startTime: "7:00 pm",
    endTime: "8:30 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/fd38585a-2fc6-4221-8e6f-5ddee12174a1",
    ],
    topics: ["Linear Arrangements", "Circular arrangements"],
    skip: false,
  },
  {
    campus: NRI_CAMPUS,
    instructorName: "Ramu",
    employeeId: null,
    sheetSubject: "DSA",
    scheduledDate: "2026-07-07",
    startTime: "7:00 pm",
    endTime: "8:30 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/fbc1fc58-7a0f-4326-96b7-4f85f0077b3a",
    ],
    topics: ["Hashing", "Prefix sum K"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Siddu",
    employeeId: null,
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-07",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/4985eb0f-8e74-49cc-b105-3138fd537b51",
    ],
    topics: ["Linear Arrangements", "Circular arrangements"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Praveen Kumar",
    employeeId: null,
    sheetSubject: "Backend",
    scheduledDate: "2026-07-07",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks:
      "He is a backup instructor since no instructor is available to take the recovery classes",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/fa161f13-88f5-4b04-9c1f-a5625d9790f1",
      "https://niat-instructor-platform.ccbp.in/evaluation_report/5d68031a-5381-42fb-a8c4-dfd138bfe735",
    ],
    topics: ["Introduction to Backend Development", "Introduction to ExpressJs part-1"],
    skip: false,
  },
  {
    campus: NRI_CAMPUS,
    instructorName: "",
    employeeId: null,
    sheetSubject: "",
    scheduledDate: "2026-07-08",
    startTime: "7:00 pm",
    endTime: "8:30 pm",
    remarks: "Session cancelled, since holidays was announced in NRI campus",
    qaReportUrls: [],
    topics: [],
    skip: true,
    skipReason: "Cancelled (campus holiday)",
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Tejaswini Sirigiri",
    employeeId: null,
    sheetSubject: "Math",
    scheduledDate: "2026-07-08",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "No students joined the session",
    qaReportUrls: [],
    topics: ["Introduction to Probability & Statistics in ML", "Introduction to Statistics & Datasets"],
    skip: true,
    skipReason: "No students joined",
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Raghavendar",
    employeeId: null,
    sheetSubject: "DSA",
    scheduledDate: "2026-07-08",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/c6fd8cc4-7243-4c84-b701-d589b15d019e",
    ],
    topics: ["Hashing", "Prefix sum K"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Mir Nabeel",
    employeeId: null,
    sheetSubject: "Math",
    scheduledDate: "2026-07-09",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/9817d5ba-f37d-4e31-88f0-feeb529da21b",
    ],
    topics: ["Introduction to Probability & Statistics in ML", "Introduction to Statistics & Datasets"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Deepthi",
    employeeId: null,
    sheetSubject: "English",
    scheduledDate: "2026-07-10",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/daaa9a1f-689f-4e11-be6a-eef27ab40347",
    ],
    topics: ["Accuracy in sentence structure", "The Language of Connection"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Likitha",
    employeeId: null,
    sheetSubject: "English",
    scheduledDate: "2026-07-11",
    startTime: "2:30 pm",
    endTime: "4:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/4c33c020-d185-4530-87cd-77b8680c504a",
    ],
    topics: ["Accuracy in sentence structure", "The Language of Connection"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Praveen Kumar",
    employeeId: null,
    sheetSubject: "Backend",
    scheduledDate: "2026-07-11",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/0e283fee-c938-41c7-b8d6-db2768c17980",
    ],
    topics: ["Introduction to Backend Development", "Introduction to ExpressJs part-1"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Jammu Tejaswini",
    employeeId: null,
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-13",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/0a19943a-9f03-44e7-a775-c675b60e9be1",
    ],
    topics: ["Linear Arrangements", "Circular arrangements"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Nitish Kumar",
    employeeId: null,
    sheetSubject: "DSA",
    scheduledDate: "2026-07-13",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/151cb941-c4d2-4af3-8e2a-58fddff76f87",
    ],
    topics: ["Sliding Window, Two-Pointer Technique", "Longest Subarray with Sum K"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Kavya",
    employeeId: null,
    sheetSubject: "Backend",
    scheduledDate: "2026-07-14",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/727f6618-6a68-49a3-a3f2-142068ccf63f",
    ],
    topics: ["Introduction to ExpressJs part-2", "Introduction to ExpressJs part-3"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Tharuni",
    employeeId: null,
    sheetSubject: "Gen AI",
    scheduledDate: "2026-07-14",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/c673525f-02da-415f-a469-e79832bec9c8",
    ],
    topics: ["Mastering image generation", "setting kaggle environment"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Izhaar",
    employeeId: null,
    sheetSubject: "Gen AI",
    scheduledDate: "2026-07-15",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/e1e31c1d-7e05-4588-9684-070ddfb42bb2",
      "https://niat-instructor-platform.ccbp.in/evaluation_report/2391190b-4651-447e-8ac1-888fc9286b25",
    ],
    topics: ["Introduction to AI For Finance", "Building Personal Finance Advisor"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Tejaswini Sirigiri",
    employeeId: null,
    sheetSubject: "Math",
    scheduledDate: "2026-07-15",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/5467d964-a6c3-4ef6-ac20-31817b0ccd3d",
    ],
    topics: [
      "Introduction to Probability & Statistics in ML",
      "Introduction to Statistics & Datasets",
      "Data Visualisation 1",
    ],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Mir Nabeel",
    employeeId: null,
    sheetSubject: "Math",
    scheduledDate: "2026-07-16",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Few students are making disturbance in the session",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/33d95776-3450-4329-afc6-8ab6cc05ecf9",
    ],
    topics: ["Data Visualization - I", "Data Visualization - II"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Deepthi",
    employeeId: null,
    sheetSubject: "English",
    scheduledDate: "2026-07-16",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/a1129f08-3fa5-4c9a-a6e3-500410d55787",
    ],
    topics: ["Mastering the Art of Discussion", "Designing Clear Prompts"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Sai Kiran",
    employeeId: null,
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-17",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [],
    topics: ["Blood Relations 1"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Tejaswini Sirigiri",
    employeeId: null,
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-17",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/5467d964-a6c3-4ef6-ac20-31817b0ccd3d",
    ],
    topics: ["Blood Relations 1", "Blood Relations 2"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Likitha",
    employeeId: null,
    sheetSubject: "English",
    scheduledDate: "2026-07-18",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/ad0ac504-1f1c-4204-8af4-bd98b741f133",
      "https://niat-instructor-platform.ccbp.in/evaluation_report/4a375d27-3f5a-46ad-bad0-c051bccb6b9d",
    ],
    topics: ["Mastering the Art of Discussion", "Designing Clear Prompts"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Nithish kumar",
    employeeId: null,
    sheetSubject: "DSA",
    scheduledDate: "2026-07-18",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Session Cancelled since no student joined",
    qaReportUrls: [],
    topics: [],
    skip: true,
    skipReason: "Cancelled, no student joined",
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Sai Kiran",
    employeeId: null,
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-20",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Completed 6 classroom quizzes and 2 topics session delivery",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/0d9f4115-7087-4428-b24a-20e4d06e8599",
    ],
    topics: ["Blood Relations 2", "Venn Diagrams"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Penuboina Vamshi",
    employeeId: null,
    sheetSubject: "Backend",
    scheduledDate: "2026-07-20",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/904b64cb-8dd7-4248-873a-289892fa8dac",
    ],
    topics: ["Introduction to ExpressJs part-2", "Introduction to ExpressJs part-3"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Gattadi Vikranth",
    employeeId: null,
    sheetSubject: "DSA",
    scheduledDate: "2026-07-21",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/9d89b6a3-79a7-4ef6-80f7-51b14202b18a",
      "https://niat-instructor-platform.ccbp.in/evaluation_report/f5e51404-dedf-4625-a698-b438e2d45908",
    ],
    topics: ["Sliding Window, Two-Pointer Technique", "Longest Subarray with Sum K"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Nithish kumar",
    employeeId: null,
    sheetSubject: "DSA",
    scheduledDate: "2026-07-21",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/94ff2a2e-ff43-48a0-ac9a-a6ac5c7b5c59",
    ],
    topics: ["Largest Subarray Sum", "Two Sum"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "divya partipati",
    employeeId: null,
    sheetSubject: "Backend",
    scheduledDate: "2026-07-22",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Audio was not recorded",
    qaReportUrls: [],
    topics: ["REST APIs", "Debugging Common Errors"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Tejaswini Sirigiri",
    employeeId: null,
    sheetSubject: "Math",
    scheduledDate: "2026-07-22",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/d0ca5064-8fb5-4257-a1f7-018fafcd2cb1",
    ],
    topics: ["Data Visualization - 2", "Measures of Central Tendency topics"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Sai Kiran",
    employeeId: null,
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-23",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/bf11b4bd-e3b6-43c3-b392-2f9cc788e710",
    ],
    topics: ["Syllogisms -1", "Syllogisms -2"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Tharuni",
    employeeId: null,
    sheetSubject: "Gen Ai",
    scheduledDate: "2026-07-23",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/48d7712e-e8b2-4a9f-9735-02e45a5b863b",
    ],
    topics: ["Mastering Image Generation with Stable Diffusion", "Mastering ai audio generation"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Mir Nabeel",
    employeeId: "NW0004716",
    sheetSubject: "Math",
    scheduledDate: "2026-07-25",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/ddc6914b-4977-48ca-a2b5-05e6df1c3758",
    ],
    topics: ["Measures of central tendency", "Measures of variability"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Siddu",
    employeeId: "NW0004948",
    sheetSubject: "Aptitude",
    scheduledDate: "2026-07-25",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [],
    topics: ["Venn Diagrams", "Syllogisms - 1", "Syllogisms - 2"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Ayan Chakraborty",
    employeeId: "NW0004813",
    sheetSubject: "Backend",
    scheduledDate: "2026-07-27",
    startTime: "6:30 pm",
    endTime: "8:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/c095b72b-e855-4909-8161-53986a4d22f4",
    ],
    topics: ["Debugging Common Errors | Part 2", "Authentication - 1"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Ponneboina Vamshi",
    employeeId: "NW0005204",
    sheetSubject: "Backend",
    scheduledDate: "2026-07-27",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [],
    topics: ["REST API's"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Attar Asif",
    employeeId: "NW0004118",
    sheetSubject: "DSA",
    scheduledDate: "2026-07-28",
    startTime: "6:30 pm",
    endTime: "8:00 pm",
    remarks: "",
    qaReportUrls: [],
    topics: ["Largest Subarray Sum", "Two Sum"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Nitish Kumar dameruppula",
    employeeId: "NW0005243",
    sheetSubject: "DSA",
    scheduledDate: "2026-07-28",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [],
    topics: ["Introduction to Linked List"],
    skip: false,
  },
  {
    // NOTE: sheet says "30/1/2026" (Jan 30), but every neighboring row runs
    // 4 Jul - 11 Aug 2026 and this one sits between the 28 Jul and 3 Aug
    // rows -- almost certainly a typo for 30 Jul 2026. Kept as the literal
    // sheet date and flagged; confirm before committing.
    campus: MRV_CAMPUS,
    instructorName: "Tejaswini Sirigiri",
    employeeId: "NW0003728",
    sheetSubject: "Math",
    scheduledDate: "2026-01-30",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "",
    qaReportUrls: [],
    topics: ["Measures of Variability", "Skewness,Kurtosis&Outliers"],
    skip: false,
    flagForReview: true,
    flagReason:
      'Date reads "30/1/2026" in the sheet but sits chronologically between 28 Jul and 3 Aug rows -- likely means 30/7/2026. Confirm before import.',
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Mir Nabeel",
    employeeId: "NW0004716",
    sheetSubject: "Math",
    scheduledDate: "2026-08-03",
    startTime: "6:30 pm",
    endTime: "8:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/9dede134-1674-49f2-8a56-0cfdc3f3c123",
    ],
    topics: ["Skewness,Kurtosis&Outliers", "Basics_of_Probability"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Bussa Tharuni",
    employeeId: "NW0005096",
    sheetSubject: "Gen Ai",
    scheduledDate: "2026-08-03",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Class Cancelled due to less strength",
    qaReportUrls: [],
    topics: ["building no code application with ai"],
    skip: true,
    skipReason: "Cancelled due to low strength",
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Bandi Jaswanth Reddy",
    employeeId: "NW0004017",
    sheetSubject: "Aptitude",
    scheduledDate: "2026-08-04",
    startTime: "6:30 pm",
    endTime: "8:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/578c89ea-18b9-4579-b393-e8e6b726b3ab",
    ],
    topics: ["Cubes", "Puzzles"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Attar Asif",
    employeeId: "NW0004118",
    sheetSubject: "DSA",
    scheduledDate: "2026-08-05",
    startTime: "6:30 pm",
    endTime: "8:00 pm",
    remarks: "",
    qaReportUrls: [],
    topics: ["Introduction to Linked List"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Irlapati Avinash",
    employeeId: "NW0004023",
    sheetSubject: "Backend",
    scheduledDate: "2026-08-06",
    startTime: "6:30 pm",
    endTime: "8:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/04435407-a883-45d5-a64c-02923739abbc",
    ],
    topics: ["Authentication part 2"],
    skip: false,
  },
  {
    campus: CDU_CAMPUS_NAME,
    instructorName: "Mohammad Izhaar Ahmed",
    employeeId: "NW0004228",
    sheetSubject: "Gen AI",
    scheduledDate: "2026-08-07",
    startTime: "6:30 pm",
    endTime: "8:00 pm",
    remarks: "",
    qaReportUrls: [
      "https://niat-instructor-platform.ccbp.in/evaluation_report/506f7347-af7e-49ec-97a5-42d75897cb33",
      "https://niat-instructor-platform.ccbp.in/evaluation_report/b35cda76-650d-413d-b140-8c69e2ffb9e7",
    ],
    topics: ["Introduction to RAG evaluation", "Enhancing productivity with AI"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Nitish Kumar dameruppula",
    employeeId: "NW0005243",
    sheetSubject: "DSA",
    scheduledDate: "2026-08-06",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Class Cancelled due to less strength",
    qaReportUrls: [],
    topics: ["Insertion in linked llist", "Deletion in Linked List"],
    skip: true,
    skipReason: "Cancelled due to low strength",
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Cheeli Lalitha Sowndarya Deepthi",
    employeeId: "NW0004069",
    sheetSubject: "English",
    scheduledDate: "2026-08-07",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Only 2 students joined the session",
    qaReportUrls: [],
    topics: ["1) Framing Effective Questions", "2) Emphasizing Self-Expression"],
    skip: false,
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Kakaraparthi Tarak Sai",
    employeeId: "NW2000295",
    sheetSubject: "NodeJS",
    scheduledDate: "2026-08-08",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Class Cancelled due to less strength",
    qaReportUrls: [],
    topics: [],
    skip: true,
    skipReason: "Cancelled due to low strength",
  },
  {
    campus: MRV_CAMPUS,
    instructorName: "Nitish Kumar dameruppula",
    employeeId: "NW0005243",
    sheetSubject: "DSA",
    scheduledDate: "2026-08-11",
    startTime: "5:30 pm",
    endTime: "7:00 pm",
    remarks: "Class cancelled due to 0 joinees for the session",
    qaReportUrls: [],
    topics: [],
    skip: true,
    skipReason: "Cancelled, 0 joinees",
  },
];
